---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  remote_user: root
  gather_facts: no
  roles:
    #- role: rhel
      #when: os == "rhel"

    - role: jeus
    - role: webtob
      #when: services["apache"] is defined
  #  - role: webtob


