---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  remote_user: root
  gather_facts: yes
  roles:
    - role: rhel
      when: os == "rhel"

    - role: jeus
      when: services["apache"] is defined
  #  - role: webtob


