---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  remote_user: root
  gather_facts: yes
  pre_tasks:
    - name: Collect facts
      setup:
  roles:
    - role: rhel
    - role: jeus
    - role: webtob


