- name: get http.m directory
  find:
    paths: "/shcsw"
    recurse: yes
    file_type: file
    patterns: 'http.m'
  register: file

#- name: print domain.xml file path
#  debug:
#    msg: "{{ file }}"
#
#- name: print domain.xml file path
#  debug:
#    msg: "{{ item.path }}"
#  with_items: "{{ file.files }}"

- name: set http.m file path as fact
  ansible.builtin.set_fact:
    config_dir: "{{ item.path }}"
  with_items: "{{ file.files }}"

- name: display xml file contents
  set_fact: var="{{ item }}"
  with_file:
    - "{{ config_dir }}"

- name: set json converted httpm config as fact
  set_fact:
    content_json: "{{ config_dir | httpm2json }}"

- name: print converted httpm as json var
  debug:
    msg: "{{content_json}}, {{config_dir}}"

