- name: get domain.xml directory
  find:
    paths: "/shcsw"
    recurse: yes
    file_type: file
    patterns: 'domain.xml'
  register: file

- name: set domain.xml file path as fact
  ansible.builtin.set_fact:
    config_dir: "{{ item.path }}"
  with_items: "{{ file.files }}"

- name: read xml file contents
  slurp:
    src: "{{ config_dir }}"
  register: var

- name: set config content as fact
  set_fact:
    config_data: "{{ var.content | b64decode }}"

- name: display config file contents
  debug:
    msg: "{{ config_data }}" #"{{ config_data }}"


- name: set json converted jeus config as fact
  set_fact:
    content_json: "{{ config_data | xml2json }}"


- name: print converted domain.xml as json var
  debug:
    msg: "{{content_json}}, {{config_dir}}"

#- name: scanning Jeus Configuration

#- name: scanning WebtoB Configuration

#- name: update configurations


      #failed_when:
      #  - "'FAILED' in console.stderr"
      #  - '"Error" in console.stdout'
  #  debug: var=console.stdout_lines
