- name: get domain.xml directory
  find:
    paths: "/shcsw"
    recurse: yes
    file_type: file
    patterns: 'domain.xml'
  register: file

#- name: print domain.xml file path
#  debug:
#    msg: "{{ file }}"
#
#- name: print domain.xml file path
#  debug:
#    msg: "{{ item.path }}"
#  with_items: "{{ file.files }}"

- name: set domain.xml file path as fact
  ansible.builtin.set_fact:
    config_dir: "{{ item.path }}"
  with_items: "{{ file.files }}"

- name: display xml file contents
  set_fact: var="{{ item }}"
  with_file:
    - "{{ config_dir }}"

- name: set json converted jeus config as fact
  set_fact:
    content_json: "{{ var | xml2json }}"

- name: print converted domain.xml as json var
  debug:
    msg: "{{content_json}}, {{config_dir}}"

#- name: scanning Jeus Configuration

#- name: scanning WebtoB Configuration

#- name: update configurations


      #failed_when:
      #  - "'FAILED' in console.stderr"
      #  - '"Error" in console.stdout'
  #  debug: var=console.stdout_lines
