- name: scanning yum
  yum:
    list=installed
  register: yum_packages

- debug:
    var: yum_packages

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Print the package facts
  ansible.builtin.debug:
    var: ansible_facts.packages

- name: Collect facts
  setup:
